FROM node:8.10-alpine

#ENV NODE_ENV=production

RUN apk update \
  && apk upgrade \
  && apk add --no-cache \
    git \
    make \
    gcc \
    g++ \
    python \
    bash \
    openssh

WORKDIR /bitcore

RUN npm config set unsafe-perm true
COPY package*.json ./
COPY lerna.json ./
RUN npm install

COPY ./packages/bitcore-build/package.json ./packages/bitcore-build/package.json
COPY ./packages/bitcore-mnemonic/package.json ./packages/bitcore-mnemonic/package.json
COPY ./packages/bitcore-lib/package.json ./packages/bitcore-lib/package.json
COPY ./packages/bitcore-lib-cash/package.json ./packages/bitcore-lib-cash/package.json
COPY ./packages/bitcore-p2p/package.json ./packages/bitcore-p2p/package.json
COPY ./packages/bitcore-p2p-cash/package.json ./packages/bitcore-p2p-cash/package.json
COPY ./packages/bitcore-wallet-client/package.json ./packages/bitcore-wallet-client/package.json
COPY ./packages/bitcore-client/package.json ./packages/bitcore-client/package.json
#COPY ./packages/bitcore-wallet/package.json ./packages/bitcore-wallet/package.json
#COPY ./packages/bitcore-wallet-client/package.json ./packages/bitcore-wallet-client/package.json
#COPY ./packages/bitcore-wallet-service/package.json ./packages/bitcore-wallet-service/package.json
COPY ./packages/bitcore-node/package.json ./packages/bitcore-node/package.json
COPY ./packages/insight-previous/package.json ./packages/insight-previous/package.json

RUN ./node_modules/.bin/lerna bootstrap

COPY . .

RUN rm -rf \
  ./packages/bitcore-wallet \
  ./packages/bitcore-wallet-client \
  ./packages/bitcore-wallet-service \
  ./packages/insight

RUN apk del \
  git \
  make \
  gcc \
  g++

RUN rm /var/cache/apk/*
CMD ["./node_modules/.bin/lerna", "run", "start"]
