FROM rust as builder
ENV GIT_REPO=https://github.com/blockstack/bitcoin-p2p-firewall

WORKDIR /src/
RUN git clone ${GIT_REPO}
RUN cargo install --path /src/bitcoin-p2p-firewall


FROM alpine
COPY --from=builder /usr/local/cargo/bin/bitcoin-p2p-firewalld /usr/local/bin/bitcoin-p2p-firewalld
CMD [ "/usr/local/bin/bitcoin-p2p-firewalld -n regtest -b block,cmpctblock 18444 bitcoin_regtest.bitcoind:28443" ]
